"""Rendering and output checks for the generated workflow inventory."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def escape_markdown_table_value(value: str) -> str:
    return value.replace("|", "\\|")


def markdown_value(value: Any) -> str:
    if value is None or value == [] or value == {}:
        return "none"
    if isinstance(value, dict):
        rendered = ", ".join(f"{key}:{item}" for key, item in value.items())
    elif isinstance(value, list):
        rendered = ", ".join(str(item) for item in value) or "none"
    else:
        rendered = str(value)
    return escape_markdown_table_value(rendered)


def render_markdown(inventory: dict[str, Any]) -> str:
    lines = [
        "# DCOIR GitHub Workflow Inventory",
        "",
        f"- schema_version: `{inventory['schema_version']}`",
        f"- governing_issue: `#{inventory['governing_issue']}`",
        f"- primary_workflow_count: `{inventory['workflow_count']}`",
        f"- reusable_workflow_count: `{inventory['reusable_workflow_count']}`",
        f"- composite_action_count: `{inventory['composite_action_count']}`",
        f"- local_reusable_workflow_calls: `{inventory['local_reusable_workflow_calls']}`",
        f"- local_composite_action_calls: `{inventory['local_composite_action_calls']}`",
        f"- contract_registry: `{inventory['contract_registry']}`",
        "",
        "This inventory is generated by `project_sources/github_actions/tools/build_workflow_inventory.py`.",
        "Regenerate it after workflow, reusable workflow, composite action, report, or workflow-tooling changes.",
        "",
        "| File | Workflow name | Triggers | Permissions | Secrets/vars | Artifacts | Report family | Contract family | Status | Risk |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for item in inventory["workflows"]:
        lines.append(
            "| {file} | {name} | {triggers} | {permissions} | {secrets} | {artifacts} | {report} | {contract} | {status} | {risk} |".format(
                file=f"`{item['file']}`",
                name=markdown_value(item["workflow_name"]),
                triggers=markdown_value(item["trigger_events"]),
                permissions=markdown_value(item["permissions"]),
                secrets=markdown_value(item["secret_or_var_count"]),
                artifacts=markdown_value(item["artifacts"]),
                report=markdown_value(item["report_family"]),
                contract=markdown_value(item["contract_family"]),
                status=markdown_value(item["migration_status"]),
                risk=markdown_value(item["risk"]),
            )
        )
    lines.extend([
        "",
        "The full per-workflow target architecture, rollback, and acceptance-evidence plan lives in",
        "`project_sources/github_actions/workflow_modularization_contracts.json` so the generated",
        "inventory stays compact and reviewable.",
        "",
    ])
    return "\n".join(lines).rstrip() + "\n"


def write_outputs(inventory: dict[str, Any], json_output: Path, markdown_output: Path) -> None:
    json_output.write_text(json.dumps(inventory, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8")
    markdown_output.write_text(render_markdown(inventory), encoding="utf-8")


def check_outputs(inventory: dict[str, Any], json_output: Path, markdown_output: Path) -> list[str]:
    findings: list[str] = []
    expected_json = json.dumps(inventory, sort_keys=True, separators=(",", ":")) + "\n"
    expected_markdown = render_markdown(inventory)
    if not json_output.exists():
        findings.append(f"{json_output}:1: generated workflow inventory JSON is missing")
    elif json_output.read_text(encoding="utf-8") != expected_json:
        findings.append(f"{json_output}:1: generated workflow inventory JSON is stale; rerun build_workflow_inventory.py")
    if not markdown_output.exists():
        findings.append(f"{markdown_output}:1: generated workflow inventory Markdown is missing")
    elif markdown_output.read_text(encoding="utf-8") != expected_markdown:
        findings.append(f"{markdown_output}:1: generated workflow inventory Markdown is stale; rerun build_workflow_inventory.py")
    return findings
