#!/usr/bin/env python3
"""Compatibility facade for workflow YAML parsing helpers."""
from __future__ import annotations

from powershell_surface_inventory_yaml_part_01 import (
    line_indent,
    yaml_item_text,
    yaml_item_text_without_comment,
    strip_yaml_node_prefixes,
    normalize_workflow_scalar,
    workflow_scalar_is_alias,
    yaml_mapping_key_indent,
    yaml_key_name,
    previous_parent_index,
    unquoted_flow_collection_value,
    flow_mapping_pieces,
    flow_collection_shape_error,
    nested_content_index,
    block_end_line,
    normalize_block_scalar_command,
    strip_yaml_inline_comment,
    strip_yaml_inline_comment_with_quote,
    yaml_unclosed_quote,
    yaml_quote_can_start,
    is_yaml_block_scalar_marker,
    yaml_block_scalar_indent_indicator,
    yaml_block_scalar_content_indent,
    is_invalid_block_scalar_like_value,
    parent_block_start,
    clean_shell_value,
    shell_line_without_comment,
    command_text_for_marker_scan,
)
from powershell_surface_inventory_yaml_part_02 import (
    cleaned_workflow_string,
    empty_workflow_string,
    direct_child_key,
    executable_steps_key,
    defaults_run_shell_key,
    defaults_run_mapping_key,
    unsupported_workflow_shell_value,
    flow_mapping_fragment_error,
    flow_mapping_has_direct_key,
    unsupported_workflow_run_value,
    unsupported_inline_executable_steps_key,
    block_scalar_has_nonblank_content,
    has_block_collection_child,
    collect_run_block,
    split_flow_mapping,
    shell_executable,
    is_powershell_shell,
    inline_shell_value,
    defaults_inline_shell,
    run_inline_shell,
    step_line_has_ancestor_key,
    step_child_ancestor_key,
    line_is_within_step_run_block_scalar,
    misindented_step_workflow_key,
)
from powershell_surface_inventory_yaml_part_03 import (
    step_blocks,
    direct_step_mapping_key,
    unsupported_flow_step_mapping_key,
    empty_block_scalar_run_key,
    unsupported_block_scalar_workflow_string_key,
    nonscalar_workflow_string_value_key,
    direct_defaults_shell,
    workflow_default_shell,
    job_default_shell,
    default_shell_for_steps,
)
