#!/usr/bin/env python3
"""Validate PowerShell finding baseline, remediation, and suppression governance.

Compatibility facade for connector-sized finding-governance helper modules.
"""
from __future__ import annotations

from powershell_finding_governance_classification import (
    classify_findings,
    exception_approves_missing,
    finding_matches_baseline,
    finding_matches_rule,
    finding_matches_suppression,
    governance_summary,
    path_prefix_matches,
)
from powershell_finding_governance_cli import build_report, main, parse_args
from powershell_finding_governance_common import (
    ALLOWED_DECISIONS,
    ASSEMBLY_PARITY_SCHEMA_VERSION,
    DEFAULT_ANALYZER_REPORT,
    DEFAULT_ASSEMBLY_PARITY_REPORT,
    DEFAULT_CUSTOM_REPORT,
    DEFAULT_GOVERNANCE,
    DEFAULT_JSON_OUTPUT,
    DEFAULT_MARKDOWN_OUTPUT,
    DEFAULT_RULE_RISK_REPORT,
    EXPIRY_OR_REVISIT_FIELDS,
    GOVERNANCE_SCHEMA_VERSION,
    ISSUE_NUMBER,
    LINE_OR_LOCATOR_FIELDS,
    REPORT_SCHEMAS,
    REVIEW_FIELDS,
    SCHEMA_VERSION,
    SEVERITY_ORDER,
    Finding,
    GovernanceError,
    has_any_text,
    is_blanket_selector,
    is_windows_drive_path,
    mark_report_write_failure,
    normalize_date,
    read_json,
    resolve_repo_input_path,
    resolve_repo_output_path,
    safe_repo_path,
    scalar,
    severity_rank,
    sha256_text,
    slash_path,
    validate_governance_path,
    validate_governance_path_prefix,
    write_json,
)
from powershell_finding_governance_reporting import render_markdown, write_outputs
from powershell_finding_governance_sources import (
    collect_findings,
    generated_output_paths,
    load_doc,
    load_optional_doc,
    normalize_finding,
    report_validation_success_state,
    stable_fingerprint,
    validate_assembly_parity_report,
)
from powershell_finding_governance_validation import (
    validate_baseline_record,
    validate_governance_doc,
    validate_review_fields,
    validate_rule_path_selectors,
    validate_suppression,
)


__all__ = [
    "ALLOWED_DECISIONS",
    "ASSEMBLY_PARITY_SCHEMA_VERSION",
    "DEFAULT_ANALYZER_REPORT",
    "DEFAULT_ASSEMBLY_PARITY_REPORT",
    "DEFAULT_CUSTOM_REPORT",
    "DEFAULT_GOVERNANCE",
    "DEFAULT_JSON_OUTPUT",
    "DEFAULT_MARKDOWN_OUTPUT",
    "DEFAULT_RULE_RISK_REPORT",
    "EXPIRY_OR_REVISIT_FIELDS",
    "GOVERNANCE_SCHEMA_VERSION",
    "ISSUE_NUMBER",
    "LINE_OR_LOCATOR_FIELDS",
    "REPORT_SCHEMAS",
    "REVIEW_FIELDS",
    "SCHEMA_VERSION",
    "SEVERITY_ORDER",
    "Finding",
    "GovernanceError",
    "build_report",
    "classify_findings",
    "collect_findings",
    "exception_approves_missing",
    "finding_matches_baseline",
    "finding_matches_rule",
    "finding_matches_suppression",
    "generated_output_paths",
    "governance_summary",
    "has_any_text",
    "is_blanket_selector",
    "is_windows_drive_path",
    "load_doc",
    "load_optional_doc",
    "main",
    "mark_report_write_failure",
    "normalize_date",
    "normalize_finding",
    "parse_args",
    "path_prefix_matches",
    "read_json",
    "render_markdown",
    "report_validation_success_state",
    "resolve_repo_input_path",
    "resolve_repo_output_path",
    "safe_repo_path",
    "scalar",
    "severity_rank",
    "sha256_text",
    "slash_path",
    "stable_fingerprint",
    "validate_assembly_parity_report",
    "validate_baseline_record",
    "validate_governance_doc",
    "validate_governance_path",
    "validate_governance_path_prefix",
    "validate_review_fields",
    "validate_rule_path_selectors",
    "validate_suppression",
    "write_json",
    "write_outputs",
]


if __name__ == "__main__":
    raise SystemExit(main())
