assignment_text = "\n".join(
    [
        f"OPENROUTER_API_KEY={openrouter_key}",
        f"OPENAI_API_KEY={openai_key}",
        f"password={password_value}",
        f"password={punctuation_password}",
        f"password={dotted_password}",
        f"PASSWORD={delimiter_password}",
        f"api-key: {yaml_password}",
        f"Authorization: Bearer {bearer_secret}",
        f'Authorization: Bearer "{bearer_secret}"',
        f"Proxy-Authorization: Basic '{basic_secret}'",
        f'Authorization: token "{github_secret_fallback}"',
        f"Proxy-Authorization: Basic {basic_secret}",
        f"Cookie: {cookie_secret}",
        f"Set-Cookie: {set_cookie_secret}",
        f"X-Api-Key: {single_quoted_api_key}",
        f'"Authorization": "Bearer {bearer_secret}"',
        f'Authorization: "Bearer {bearer_secret}"',
        f'Authorization: Bearer {bearer_secret}',
        f'headers = {{ Authorization: "Bearer {bearer_secret}" }}',
        f'headers = {{ Cookie: "{cookie_secret}" }}',
        f'Authorization: "Bearer {bearer_secret}"',
        f"'Proxy-Authorization': 'Basic {basic_secret}'",
        f'"Cookie": "{cookie_secret}"',
        f'"Set-Cookie": f"{set_cookie_secret}"',
        f'"X-Api-Key": "token {single_quoted_api_key}"',
        f"curl -H \"Authorization: Bearer {bearer_secret}\" https://example.test/",
        f"curl -udcoir:{curl_password} https://example.test/",
        f"curl -u dcoir:{curl_password} https://example.test/",
        f"curl --user dcoir:{curl_password} https://example.test/",
        f"curl --user=dcoir:{curl_password} https://example.test/",
        f"curl -u :{curl_password} https://example.test/",
        f"curl -u:{curl_password} https://example.test/",
        f"curl --user :{curl_password} https://example.test/",
        f"curl --user=:{curl_password} https://example.test/",
        f"curl --proxy-user dcoir:{curl_proxy_password} https://example.test/",
        f"curl --proxy-user=dcoir:{curl_proxy_password} https://example.test/",
        f"curl --proxy-user :{curl_proxy_password} https://example.test/",
        f"curl --proxy-user=:{curl_proxy_password} https://example.test/",
        f"curl -u ':{curl_spaced_password}' https://example.test/",
        f"curl -u':{curl_spaced_password}' https://example.test/",
        f'curl --user ":{curl_spaced_password}" https://example.test/',
        f'curl --user=":{curl_spaced_password}" https://example.test/',
        f"curl -u 'dcoir:{curl_spaced_password}' https://example.test/",
        f"curl -u'dcoir:{curl_spaced_password}' https://example.test/",
        f'curl --user "dcoir:{curl_spaced_password}" https://example.test/',
        f'curl --user="dcoir:{curl_spaced_password}" https://example.test/',
        f'curl --proxy-user "dcoir:{curl_spaced_password}" https://example.test/',
        f"curl -u :{curl_fallback_expression} https://example.test/",
        f"curl -u:{curl_fallback_expression} https://example.test/",
        f"curl --user :{curl_fallback_expression} https://example.test/",
        f"curl --user=:{curl_fallback_expression} https://example.test/",
        f"curl --proxy-user=:{curl_proxy_fallback_expression} https://example.test/",
        f"curl --user=:{curl_inner_brace_expression} https://example.test/",
        f"curl --user=:{curl_unclosed_expression} https://example.test/",
        f"curl -u :{curl_backtick_expression} https://example.test/",
        f"curl -u:{curl_backtick_expression} https://example.test/",
        f"curl --user :{curl_backtick_expression} https://example.test/",
        f"curl --user=:{curl_backtick_expression} https://example.test/",
        f"curl -u dcoir:{curl_backtick_expression} https://example.test/",
        f"curl -udcoir:{curl_backtick_expression} https://example.test/",
        f"curl --user dcoir:{curl_backtick_expression} https://example.test/",
        f"curl --user=dcoir:{curl_backtick_expression} https://example.test/",
        f"curl --proxy-user dcoir:{curl_backtick_expression} https://example.test/",
        f"curl --user=:{curl_multiline_backtick_expression} https://example.test/",
        f"curl --user=:{curl_multiline_backtick_tail_expression} https://example.test/",
        f'curl --user "dcoir:benign\n{curl_multiline_double_quote_password}" https://example.test/',
        f"curl --proxy-user 'proxy:benign\n{curl_multiline_single_quote_password}' https://example.test/",
        f"curl --user $'dcoir:benign\n{curl_multiline_ansi_quote_password}' https://example.test/",
        f'curl --proxy-user $"proxy:benign\n{curl_multiline_locale_quote_password}" https://example.test/',
        f"curl -u $':{curl_ansi_password}' https://example.test/",
        f"curl -u$':{curl_ansi_password}' https://example.test/",
        f"curl --user $':{curl_ansi_password}' https://example.test/",
        f"curl --user=$':{curl_ansi_password}' https://example.test/",
        f"curl --proxy-user $':{curl_ansi_password}' https://example.test/",
        f"curl -u $'dcoir:{curl_ansi_password}' https://example.test/",
        f"curl -u$'dcoir:{curl_ansi_password}' https://example.test/",
        f"curl --user $'dcoir:{curl_ansi_password}' https://example.test/",
        f"curl --user=$'dcoir:{curl_ansi_password}' https://example.test/",
        f'curl -u $":{curl_locale_password}" https://example.test/',
        f'curl -u$":{curl_locale_password}" https://example.test/',
        f'curl --user $":{curl_locale_password}" https://example.test/',
        f'curl --user=$":{curl_locale_password}" https://example.test/',
        f'curl -u $"dcoir:{curl_locale_password}" https://example.test/',
        f'curl -u$"dcoir:{curl_locale_password}" https://example.test/',
        f'curl --user $"dcoir:{curl_locale_password}" https://example.test/',
        f'curl --user=$"dcoir:{curl_locale_password}" https://example.test/',
        f"curl -u :{curl_escaped_space_password} https://example.test/",
        f"curl -u:{curl_escaped_space_password} https://example.test/",
        f"curl --user :{curl_escaped_space_password} https://example.test/",
        f"curl --user=:{curl_escaped_space_password} https://example.test/",
        f"curl -u dcoir:{curl_escaped_space_password} https://example.test/",
        f"curl -udcoir:{curl_escaped_space_password} https://example.test/",
        f"curl --user dcoir:{curl_escaped_space_password} https://example.test/",
        f"curl --user=dcoir:{curl_escaped_space_password} https://example.test/",
        f"curl --proxy-user=dcoir:{curl_escaped_space_password} https://example.test/",
        f"curl -u :concat' {curl_concat_password}' https://example.test/",
        f'curl -u:concat" {curl_concat_password}" https://example.test/',
        f"curl --user :concat$' {curl_concat_password}' https://example.test/",
        f'curl --user=:concat$" {curl_concat_password}" https://example.test/',
        f"curl -u dcoir:concat' {curl_concat_password}' https://example.test/",
        f'curl -udcoir:concat" {curl_concat_password}" https://example.test/',
        f"curl --user dcoir:concat$' {curl_concat_password}' https://example.test/",
        f'curl --user=dcoir:concat$" {curl_concat_password}" https://example.test/',
        f"curl --proxy-user=:concat' {curl_concat_password}' https://example.test/",
        f"machine example.test login dcoir password {netrc_password}",
        f"DATABASE_URL=postgres://dcoir:{url_password}@db.example.test/dcoir",
        f"PACKAGE_URL=https://{openrouter_key}@packages.example.test/simple",
        aws_signed_url,
        azure_sas_url,
        generic_signed_url,
        private_key_block,
        f'"password": "{quoted_json_password}"',
        f"'apiKey': '{single_quoted_api_key}'",
        f'"password": "{apostrophe_password}"',
        f"'password': '{double_quote_password}'",
        f'"password": "{escaped_quote_password}"',
        f'"apiKey": "{quoted_env_reference}"',
        f'"password": "{dollar_env_reference}"',
        f'"token": "{process_env_reference}"',
        f'"token": "{github_secret_reference}"',
        f'"token": \'{exact_os_getenv_reference}\'',
        f'"secret": \'{exact_secrets_reference}\'',
        f'"Authorization": "Bearer {quoted_env_reference}"',
        f'"password": "{unsafe_process_reference}"',
        f'"token": \'{unsafe_getenv_reference}\'',
        f'"secret": \'{unsafe_secrets_reference}\'',
        f"password={unsafe_process_suffix}",
        f"token={unsafe_getenv_suffix}",
        f"token={unsafe_getenv_default}",
        f"password={unsafe_process_concat}",
        f"token={unsafe_method_concat}",
        f"password={unsafe_shell_suffix}",
        f"token={unsafe_f_string}",
        f"token: {github_secret_fallback}",
        f'curl --user="dcoir:{curl_unclosed_quoted_password} https://example.test/',
        f"curl --proxy-user='proxy:{curl_proxy_unclosed_quoted_password} https://example.test/",
    ]
)
assignment_redacted = mod.sanitize_text(assignment_text, config)
for leaked in [
    "sk-or-v1",
    "sk-proj",
    password_value,
    punctuation_password,
    dotted_password,
    delimiter_password,
    yaml_password,
    quoted_json_password,
    single_quoted_api_key,
    apostrophe_password,
    double_quote_password,
    escaped_quote_password,
    bearer_secret,
    basic_secret,
    "cookie-secret",
    "connect-secret",
    "csrf-secret",
    "refresh-cookie-secret",
    url_password,
    curl_password,
    curl_proxy_password,
    curl_spaced_password,
    "fallback curl secret",
    "proxy fallback secret",
    "fallback }} curl secret",
    "unclosed curl secret",
    "backtick curl secret",
    "multiline backtick curl secret",
    "multiline backtick tail secret",
    curl_unclosed_quoted_password,
    curl_proxy_unclosed_quoted_password,
    curl_multiline_double_quote_password,
    curl_multiline_single_quote_password,
    curl_multiline_ansi_quote_password,
    curl_multiline_locale_quote_password,
    "ansi curl secret",
    "locale curl secret",
    r"escaped\ curl\ secret",
    "concat curl secret",
    netrc_password,
    signed_url_secret,
    sas_secret,
    "PRIVATE KEY",
    "private-key-secret-material",
    "tail-secret",
    unsafe_process_reference,
    unsafe_getenv_reference,
    unsafe_secrets_reference,
    unsafe_process_suffix,
    unsafe_getenv_suffix,
    unsafe_getenv_default,
    "fallback-secret",
    "actual-secret",
    "secret-tail-123!",
]:
    assert leaked not in assignment_redacted, assignment_redacted
for preserved in [quoted_env_reference, dollar_env_reference, process_env_reference, github_secret_reference, exact_os_getenv_reference, exact_secrets_reference]:
    assert preserved in assignment_redacted, assignment_redacted
assert assignment_redacted.count("[redacted-secret]") >= 35
for safe_header in [
    '"Authorization": "Bearer ${OPENROUTER_API_KEY}"',
    'Authorization: "Bearer ${OPENROUTER_API_KEY}"',
    'headers = { Authorization: "Bearer ${OPENROUTER_API_KEY}" }',
    'Authorization: Bearer "${OPENROUTER_API_KEY}"',
]:
    assert mod.sanitize_text(safe_header, config) == safe_header
