$ErrorActionPreference = 'Stop'
$requestId = 'exec-20260520-wbs06-field-rename-apply-batch2-001'
$baseIdExpected = 'appM4KSwnVf3G3OTK'
$plan = @(
  [pscustomobject]@{ table_name='GitHub Workflow Inventory'; table_id='tblHTf5bLKGK1Yk11'; field_id='fldhfcwoRfNHkL1ya'; expected='review_after'; target='legacy_review_after_date_review'; reason='Blank across exported rows; mark as legacy review-date field rather than current workflow guidance.' },
  [pscustomobject]@{ table_name='Plans'; table_id='tblBcp5FyMIfOm7Xe'; field_id='fldCC1FicmWE2pra2'; expected='review_after'; target='legacy_review_after_date_review'; reason='Blank across exported rows; mark as legacy review-date field rather than current plan metadata.' },
  [pscustomobject]@{ table_name='Idea Inbox'; table_id='tblWwBxwrjZF6JR3r'; field_id='fldXRAz2DLHzOQmK2'; expected='source_checkpoint_id'; target='legacy_source_checkpoint_id_review'; reason='Blank provenance field; mark as legacy pending a later deletion packet.' },
  [pscustomobject]@{ table_name='Plans'; table_id='tblBcp5FyMIfOm7Xe'; field_id='fldwS46tOH9fTVQSO'; expected='created_at'; target='legacy_created_at_review'; reason='Blank text/date creation marker; mark legacy because structured/system creation metadata should carry current message.' },
  [pscustomobject]@{ table_name='Validation Evidence'; table_id='tblrPFQH2uZEYBYE9'; field_id='fldOIWWUP1cPo9zEb'; expected='release_key'; target='legacy_release_key_review'; reason='Blank across validation evidence export; mark legacy pending dependency/deletion review.' }
)
function Env([string]$n){ $v=[Environment]::GetEnvironmentVariable($n,'Process'); if([string]::IsNullOrWhiteSpace($v)){ $v=[Environment]::GetEnvironmentVariable($n,'Machine') }; if([string]::IsNullOrWhiteSpace($v)){ throw "Missing env: $n" }; return $v.Trim() }
function SaveJson($p,$o,$d=30){ $dir=Split-Path -Parent $p; if($dir -and -not(Test-Path -LiteralPath $dir)){ New-Item -ItemType Directory -Force -Path $dir|Out-Null }; $enc=New-Object System.Text.UTF8Encoding($false); [System.IO.File]::WriteAllText($p,($o|ConvertTo-Json -Depth $d),$enc) }
function Airtable($uri,$headers,$method='GET',$body=$null){ $a=@{Uri=$uri;Headers=$headers;Method=$method;ErrorAction='Stop'}; if($null -ne $body){$a.Body=($body|ConvertTo-Json -Depth 10);$a.ContentType='application/json'}; Invoke-RestMethod @a }
function FieldState($schema,$tableId,$fieldId){ $t=@($schema.tables)|Where-Object{$_.id -eq $tableId}|Select-Object -First 1; if($null -eq $t){throw "Missing table $tableId"}; $f=@($t.fields)|Where-Object{$_.id -eq $fieldId}|Select-Object -First 1; if($null -eq $f){throw "Missing field $fieldId"}; [pscustomobject]@{table=$t;field=$f} }
$repoRoot=Env 'DCOIR_REPO_ROOT'; $baseId=Env 'DCOIR_AIRTABLE_BASE_ID'; $token=Env 'DCOIR_AIRTABLE_TOKEN'
if($baseId -ne $baseIdExpected){ throw "Unexpected base id $baseId" }
$statusRoot=Join-Path $repoRoot ("chatgpt_staging\status_reports\chatgpt-exec\{0}\wbs06_field_rename_apply_batch2" -f $requestId)
if(Test-Path -LiteralPath $statusRoot){Remove-Item -LiteralPath $statusRoot -Recurse -Force}; New-Item -ItemType Directory -Force -Path $statusRoot|Out-Null
$headers=@{Authorization="Bearer $token"}; $schemaUri="https://api.airtable.com/v0/meta/bases/$baseId/tables"
$pre=Airtable $schemaUri $headers; SaveJson (Join-Path $statusRoot 'pre_schema_snapshot.json') $pre 80; SaveJson (Join-Path $statusRoot 'requested_rename_plan.json') $plan 20
$errors=New-Object System.Collections.Generic.List[string]; $precheck=New-Object System.Collections.Generic.List[object]
foreach($x in $plan){ $s=FieldState $pre $x.table_id $x.field_id; $cur=[string]$s.field.name; $dup=@($s.table.fields|Where-Object{$_.id -ne $x.field_id -and $_.name -ieq $x.target}).Count -gt 0; if($cur -ne $x.expected -and $cur -ne $x.target){$errors.Add("Schema drift $($x.table_name)/$($x.field_id): expected $($x.expected) or $($x.target), found $cur")|Out-Null}; if($dup){$errors.Add("Duplicate target $($x.target) in $($x.table_name)")|Out-Null}; $precheck.Add([pscustomobject]@{table_name=$x.table_name;field_id=$x.field_id;current_name=$cur;expected=$x.expected;target=$x.target;duplicate_target=$dup})|Out-Null }
SaveJson (Join-Path $statusRoot 'precheck.json') @($precheck.ToArray()) 20
if($errors.Count -gt 0){ $summary=[ordered]@{schema='dcoir.wbs06.field_rename_apply.v1';request_id=$requestId;result='blocked_precheck';errors=@($errors.ToArray());safety=@{field_renames_changed=0;record_updates=0;field_deletes=0;type_conversions=0;delete_queue_rows=0}}; SaveJson (Join-Path $statusRoot 'field_rename_apply_summary.json') $summary 20; throw (($errors.ToArray()) -join '; ') }
$results=New-Object System.Collections.Generic.List[object]
foreach($x in $plan){ $s=FieldState $pre $x.table_id $x.field_id; $cur=[string]$s.field.name; if($cur -eq $x.target){$status='no_op_already_current'}else{ $uri="https://api.airtable.com/v0/meta/bases/$baseId/tables/$($x.table_id)/fields/$($x.field_id)"; Airtable $uri $headers 'PATCH' @{name=$x.target}|Out-Null; $status='rename_patch_sent' }; $results.Add([pscustomobject]@{table_name=$x.table_name;table_id=$x.table_id;field_id=$x.field_id;old_name=$cur;new_name=$x.target;status=$status;reason=$x.reason})|Out-Null }
$post=Airtable $schemaUri $headers; SaveJson (Join-Path $statusRoot 'post_schema_snapshot.json') $post 80
$ver=New-Object System.Collections.Generic.List[object]; $verr=New-Object System.Collections.Generic.List[string]
foreach($x in $plan){ $s=FieldState $post $x.table_id $x.field_id; $actual=[string]$s.field.name; $ok=$actual -eq $x.target; if(-not $ok){$verr.Add("Verify failed $($x.table_name)/$($x.field_id): expected $($x.target), found $actual")|Out-Null}; $ver.Add([pscustomobject]@{table_name=$x.table_name;field_id=$x.field_id;expected_name=$x.target;verified_name=$actual;verified=$ok})|Out-Null }
$changed=@($results.ToArray()|Where-Object{$_.status -eq 'rename_patch_sent'}).Count; $noop=@($results.ToArray()|Where-Object{$_.status -eq 'no_op_already_current'}).Count; $result=if($verr.Count -eq 0){'success'}else{'verification_failed'}
$summary=[ordered]@{schema='dcoir.wbs06.field_rename_apply.v1';request_id=$requestId;result=$result;base_id=$baseId;safety=@{field_renames_requested=@($plan).Count;field_renames_changed=$changed;field_renames_noop=$noop;record_updates=0;field_deletes=0;type_conversions=0;delete_queue_rows=0};results=@($results.ToArray());verification=@($ver.ToArray());errors=@($verr.ToArray());created_utc=(Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')}
SaveJson (Join-Path $statusRoot 'field_rename_apply_results.json') @($results.ToArray()) 20; SaveJson (Join-Path $statusRoot 'field_rename_apply_verification.json') @($ver.ToArray()) 20; SaveJson (Join-Path $statusRoot 'field_rename_apply_summary.json') $summary 30
$md=@('# WBS06 field rename apply batch 2','',"- request_id: $requestId","- result: $result","- field renames changed: $changed","- field renames no-op: $noop",'- safety: no record updates, no field deletion, no type conversion, no Delete Queue rows','','| Table | Field ID | Old/current before | New verified name | Status |','|---|---|---|---|---|'); foreach($r in @($results.ToArray())){ $v=@($ver.ToArray())|Where-Object{$_.field_id -eq $r.field_id}|Select-Object -First 1; $md += "| $($r.table_name) | $($r.field_id) | $($r.old_name) | $($v.verified_name) | $($r.status) |" }; $md|Set-Content -LiteralPath (Join-Path $statusRoot 'field_rename_apply_report.md') -Encoding UTF8
if($verr.Count -gt 0){ throw (($verr.ToArray()) -join '; ') }
Write-Output ($summary|ConvertTo-Json -Depth 30)
