header_cases = {
    f'"Authorization": "Bearer {bearer_secret}"': '"Authorization": "Bearer [redacted-secret]"',
    f'Authorization: "Bearer {bearer_secret}"': 'Authorization: "Bearer [redacted-secret]"',
    f'Authorization: Bearer {bearer_secret}': 'Authorization: Bearer [redacted-secret]',
    f'Authorization: Bearer "{bearer_secret}"': 'Authorization: Bearer [redacted-secret]',
    f"Proxy-Authorization: Basic '{basic_secret}'": 'Proxy-Authorization: Basic [redacted-secret]',
    f'Authorization: token "{github_secret_fallback}"': 'Authorization: token [redacted-secret]',
    'Authorization: Bearer "${OPENROUTER_API_KEY}"': 'Authorization: Bearer "${OPENROUTER_API_KEY}"',
    f'headers = {{ Authorization: "Bearer {bearer_secret}" }}': 'headers = { Authorization: "Bearer [redacted-secret]" }',
    f'headers = {{ Cookie: "{cookie_secret}" }}': 'headers = { Cookie: "[redacted-secret]" }',
    "headers = { Cookie: sessionid=cookie-secret-123456789, X-Trace: \"keep-me\" }": "headers = { Cookie: [redacted-secret], X-Trace: \"keep-me\" }",
    "headers = { \"Set-Cookie\": sessionid=cookie-secret-123456789, X-Trace: \"keep-me\" }": "headers = { \"Set-Cookie\": [redacted-secret], X-Trace: \"keep-me\" }",
    "Cookie: sessionid=cookie-secret-123456789; connect.sid=connect-secret-123456789": "Cookie: [redacted-secret]",
    "headers = { Cookie: session=secret-123456, sid=second-secret-7890 }": "headers = { Cookie: [redacted-secret]}",
    "headers = { Set-Cookie: session=secret-123456, sid=second-secret-7890 }": "headers = { Set-Cookie: [redacted-secret]}",
    "headers = { Cookie: session=secret-123456, sid=second-secret-7890, X-Trace: \"keep-me\" }": "headers = { Cookie: [redacted-secret], X-Trace: \"keep-me\" }",
    "headers = { Set-Cookie: session=secret-123456, sid=second-secret-7890, X-Trace: \"keep-me\" }": "headers = { Set-Cookie: [redacted-secret], X-Trace: \"keep-me\" }",
    "headers = { Cookie: ${COOKIE_HEADER}:actual-secret-123 }": "headers = { Cookie: [redacted-secret]}",
    "headers = { Cookie: ${COOKIE_HEADER}:actual-secret-123 } trailing_text": "headers = { Cookie: [redacted-secret]} trailing_text",
    "headers = { Cookie: ${COOKIE_HEADER} }": "headers = { Cookie: ${COOKIE_HEADER} }",
    "headers = { Set-Cookie: ${COOKIE_HEADER}:actual-secret-123 }": "headers = { Set-Cookie: [redacted-secret]}",
    "headers = { Set-Cookie: ${COOKIE_HEADER} }": "headers = { Set-Cookie: ${COOKIE_HEADER} }",
    "headers = { Cookie: ${{ secrets.COOKIE_HEADER }} }": "headers = { Cookie: ${{ secrets.COOKIE_HEADER }} }",
    "Cookie: session=secret-123456, sid=second-secret-7890": "Cookie: [redacted-secret]",
    "Set-Cookie: session=secret-123456, sid=second-secret-7890": "Set-Cookie: [redacted-secret]",
    "headers = { Cookie: ${COOKIE_HEADER}, X-Trace: \"keep-me\" }": "headers = { Cookie: ${COOKIE_HEADER}, X-Trace: \"keep-me\" }",
    f'headers = {{ Authorization: Bearer {bearer_secret}, X-Trace: "keep-me" }}': 'headers = { Authorization: Bearer [redacted-secret], X-Trace: "keep-me" }',
    f'headers = {{ Authorization: Bearer {bearer_secret} }}': 'headers = { Authorization: Bearer [redacted-secret] }',
    f'Authorization: Bearer {bearer_secret}\nnext: field': 'Authorization: Bearer [redacted-secret]\nnext: field',
}
for unsafe_header, expected_header in header_cases.items():
    assert mod.sanitize_text(unsafe_header, config) == expected_header
curl_cases = {
    f"curl -uuser:{curl_password} https://example.test/": "curl -uuser:[redacted-secret] https://example.test/",
    f"curl -u user:{curl_password} https://example.test/": "curl -u user:[redacted-secret] https://example.test/",
    f"curl --user user:{curl_password} https://example.test/": "curl --user user:[redacted-secret] https://example.test/",
    f"curl --user=user:{curl_password} https://example.test/": "curl --user=user:[redacted-secret] https://example.test/",
    f"curl -u :{curl_password} https://example.test/": "curl -u :[redacted-secret] https://example.test/",
    f"curl -u:{curl_password} https://example.test/": "curl -u:[redacted-secret] https://example.test/",
    f"curl --user :{curl_password} https://example.test/": "curl --user :[redacted-secret] https://example.test/",
    f"curl --user=:{curl_password} https://example.test/": "curl --user=:[redacted-secret] https://example.test/",
    f"curl --proxy-user proxy:{curl_proxy_password} https://example.test/": "curl --proxy-user proxy:[redacted-secret] https://example.test/",
    f"curl --proxy-user=proxy:{curl_proxy_password} https://example.test/": "curl --proxy-user=proxy:[redacted-secret] https://example.test/",
    f"curl --proxy-user :{curl_proxy_password} https://example.test/": "curl --proxy-user :[redacted-secret] https://example.test/",
    f"curl --proxy-user=:{curl_proxy_password} https://example.test/": "curl --proxy-user=:[redacted-secret] https://example.test/",
    f"curl -u ':{curl_spaced_password}' https://example.test/": "curl -u ':[redacted-secret]' https://example.test/",
    f"curl -u':{curl_spaced_password}' https://example.test/": "curl -u':[redacted-secret]' https://example.test/",
    f'curl --user ":{curl_spaced_password}" https://example.test/': 'curl --user ":[redacted-secret]" https://example.test/',
    f'curl --user=":{curl_spaced_password}" https://example.test/': 'curl --user=":[redacted-secret]" https://example.test/',
    f"curl -u 'dcoir:{curl_spaced_password}' https://example.test/": "curl -u 'dcoir:[redacted-secret]' https://example.test/",
    f"curl -u'dcoir:{curl_spaced_password}' https://example.test/": "curl -u'dcoir:[redacted-secret]' https://example.test/",
    f'curl --user "dcoir:{curl_spaced_password}" https://example.test/': 'curl --user "dcoir:[redacted-secret]" https://example.test/',
    f'curl --user="dcoir:{curl_spaced_password}" https://example.test/': 'curl --user="dcoir:[redacted-secret]" https://example.test/',
    f'curl --proxy-user "dcoir:{curl_spaced_password}" https://example.test/': 'curl --proxy-user "dcoir:[redacted-secret]" https://example.test/',
    f"curl -u :{curl_fallback_expression} https://example.test/": "curl -u :[redacted-secret] https://example.test/",
    f"curl -u:{curl_fallback_expression} https://example.test/": "curl -u:[redacted-secret] https://example.test/",
    f"curl --user :{curl_fallback_expression} https://example.test/": "curl --user :[redacted-secret] https://example.test/",
    f"curl --user=:{curl_fallback_expression} https://example.test/": "curl --user=:[redacted-secret] https://example.test/",
    f"curl --proxy-user=:{curl_proxy_fallback_expression} https://example.test/": "curl --proxy-user=:[redacted-secret] https://example.test/",
    f"curl --user=:{curl_inner_brace_expression} https://example.test/": "curl --user=:[redacted-secret] https://example.test/",
    f"curl --user=:{curl_unclosed_expression} https://example.test/": "curl --user=:[redacted-secret]",
    f"curl -u :{curl_backtick_expression} https://example.test/": "curl -u :[redacted-secret] https://example.test/",
    f"curl -u:{curl_backtick_expression} https://example.test/": "curl -u:[redacted-secret] https://example.test/",
    f"curl --user :{curl_backtick_expression} https://example.test/": "curl --user :[redacted-secret] https://example.test/",
    f"curl --user=:{curl_backtick_expression} https://example.test/": "curl --user=:[redacted-secret] https://example.test/",
    f"curl -u dcoir:{curl_backtick_expression} https://example.test/": "curl -u dcoir:[redacted-secret] https://example.test/",
    f"curl -udcoir:{curl_backtick_expression} https://example.test/": "curl -udcoir:[redacted-secret] https://example.test/",
    f"curl --user dcoir:{curl_backtick_expression} https://example.test/": "curl --user dcoir:[redacted-secret] https://example.test/",
    f"curl --user=dcoir:{curl_backtick_expression} https://example.test/": "curl --user=dcoir:[redacted-secret] https://example.test/",
    f"curl --proxy-user dcoir:{curl_backtick_expression} https://example.test/": "curl --proxy-user dcoir:[redacted-secret] https://example.test/",
    f"curl --user=:{curl_multiline_backtick_expression} https://example.test/": "curl --user=:[redacted-secret] https://example.test/",
    f"curl --user=:{curl_multiline_backtick_tail_expression} https://example.test/": "curl --user=:[redacted-secret] https://example.test/",
    f'curl --user="dcoir:{curl_unclosed_quoted_password} https://example.test/': 'curl --user="dcoir:[redacted-secret]',
    f"curl --proxy-user='proxy:{curl_proxy_unclosed_quoted_password} https://example.test/": "curl --proxy-user='proxy:[redacted-secret]",
    f'curl --user "dcoir:benign\n{curl_multiline_double_quote_password}" https://example.test/': 'curl --user "dcoir:[redacted-secret]" https://example.test/',
    f"curl --proxy-user 'proxy:benign\n{curl_multiline_single_quote_password}' https://example.test/": "curl --proxy-user 'proxy:[redacted-secret]' https://example.test/",
    f"curl --user $'dcoir:benign\n{curl_multiline_ansi_quote_password}' https://example.test/": "curl --user $'dcoir:[redacted-secret]' https://example.test/",
    f'curl --proxy-user $"proxy:benign\n{curl_multiline_locale_quote_password}" https://example.test/': 'curl --proxy-user $"proxy:[redacted-secret]" https://example.test/',
    f"curl -u $':{curl_ansi_password}' https://example.test/": "curl -u $':[redacted-secret]' https://example.test/",
    f"curl -u$':{curl_ansi_password}' https://example.test/": "curl -u$':[redacted-secret]' https://example.test/",
    f"curl --user $':{curl_ansi_password}' https://example.test/": "curl --user $':[redacted-secret]' https://example.test/",
    f"curl --user=$':{curl_ansi_password}' https://example.test/": "curl --user=$':[redacted-secret]' https://example.test/",
    f"curl --proxy-user $':{curl_ansi_password}' https://example.test/": "curl --proxy-user $':[redacted-secret]' https://example.test/",
    f"curl -u $'dcoir:{curl_ansi_password}' https://example.test/": "curl -u $'dcoir:[redacted-secret]' https://example.test/",
    f"curl -u$'dcoir:{curl_ansi_password}' https://example.test/": "curl -u$'dcoir:[redacted-secret]' https://example.test/",
    f"curl --user $'dcoir:{curl_ansi_password}' https://example.test/": "curl --user $'dcoir:[redacted-secret]' https://example.test/",
    f"curl --user=$'dcoir:{curl_ansi_password}' https://example.test/": "curl --user=$'dcoir:[redacted-secret]' https://example.test/",
    f'curl -u $":{curl_locale_password}" https://example.test/': 'curl -u $":[redacted-secret]" https://example.test/',
    f'curl -u$":{curl_locale_password}" https://example.test/': 'curl -u$":[redacted-secret]" https://example.test/',
    f'curl --user $":{curl_locale_password}" https://example.test/': 'curl --user $":[redacted-secret]" https://example.test/',
    f'curl --user=$":{curl_locale_password}" https://example.test/': 'curl --user=$":[redacted-secret]" https://example.test/',
    f'curl -u $"dcoir:{curl_locale_password}" https://example.test/': 'curl -u $"dcoir:[redacted-secret]" https://example.test/',
    f'curl -u$"dcoir:{curl_locale_password}" https://example.test/': 'curl -u$"dcoir:[redacted-secret]" https://example.test/',
    f'curl --user $"dcoir:{curl_locale_password}" https://example.test/': 'curl --user $"dcoir:[redacted-secret]" https://example.test/',
    f'curl --user=$"dcoir:{curl_locale_password}" https://example.test/': 'curl --user=$"dcoir:[redacted-secret]" https://example.test/',
    f"curl -u :{curl_escaped_space_password} https://example.test/": "curl -u :[redacted-secret] https://example.test/",
    f"curl -u:{curl_escaped_space_password} https://example.test/": "curl -u:[redacted-secret] https://example.test/",
    f"curl --user :{curl_escaped_space_password} https://example.test/": "curl --user :[redacted-secret] https://example.test/",
    f"curl --user=:{curl_escaped_space_password} https://example.test/": "curl --user=:[redacted-secret] https://example.test/",
    f"curl -u dcoir:{curl_escaped_space_password} https://example.test/": "curl -u dcoir:[redacted-secret] https://example.test/",
    f"curl -udcoir:{curl_escaped_space_password} https://example.test/": "curl -udcoir:[redacted-secret] https://example.test/",
    f"curl --user dcoir:{curl_escaped_space_password} https://example.test/": "curl --user dcoir:[redacted-secret] https://example.test/",
    f"curl --user=dcoir:{curl_escaped_space_password} https://example.test/": "curl --user=dcoir:[redacted-secret] https://example.test/",
    f"curl --proxy-user=dcoir:{curl_escaped_space_password} https://example.test/": "curl --proxy-user=dcoir:[redacted-secret] https://example.test/",
    f"curl -u :concat' {curl_concat_password}' https://example.test/": "curl -u :[redacted-secret] https://example.test/",
    f'curl -u:concat" {curl_concat_password}" https://example.test/': "curl -u:[redacted-secret] https://example.test/",
    f"curl --user :concat$' {curl_concat_password}' https://example.test/": "curl --user :[redacted-secret] https://example.test/",
    f'curl --user=:concat$" {curl_concat_password}" https://example.test/': "curl --user=:[redacted-secret] https://example.test/",
    f"curl -u dcoir:concat' {curl_concat_password}' https://example.test/": "curl -u dcoir:[redacted-secret] https://example.test/",
    f'curl -udcoir:concat" {curl_concat_password}" https://example.test/': "curl -udcoir:[redacted-secret] https://example.test/",
    f"curl --user dcoir:concat$' {curl_concat_password}' https://example.test/": "curl --user dcoir:[redacted-secret] https://example.test/",
    f'curl --user=dcoir:concat$" {curl_concat_password}" https://example.test/': "curl --user=dcoir:[redacted-secret] https://example.test/",
    f"curl --proxy-user=:concat' {curl_concat_password}' https://example.test/": "curl --proxy-user=:[redacted-secret] https://example.test/",
}
for curl_form, expected_curl in curl_cases.items():
    assert mod.sanitize_text(curl_form, config) == expected_curl
